import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import './globals.css';

const inter = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Talk to me',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.className} bg-black text-white`}>
        {children}
      </body>
    </html>
  );
}
